version: "3.8"
services:
  project-service:
    build:
      context: ./project-service
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - PORT=8081
      - CORS_ALLOWED_ORIGINS=http://localhost:4200
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - app-network

  task-service:
    build:
      context: ./task-service
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - PORT=8082
      - CORS_ALLOWED_ORIGINS=http://localhost:4200
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    networks:
      - app-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - PORT=8080
      - CORS_ALLOWED_ORIGINS=http://localhost:4200
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
