version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  project-service:
    build:
      context: ./back/project-service
      dockerfile: Dockerfile
    container_name: project-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  user-service:
    build:
      context: ./back/user-service
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    ports:
      - "8082:8082"
    depends_on:
      - mongo

  task-service:
    build:
      context: ./back/task-service
      dockerfile: Dockerfile
    container_name: task-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    ports:
      - "8083:8083"
    depends_on:
      - mongo

volumes:
  mongo-data:
